version: '2'
services:

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - code

  php:
    build: .
    working_dir: /var/www
    volumes_from:
      - code

  code:
    image: busybox
    volumes:
      - ./:/var/www

# COPY conf/my.cnf /etc/mysql/my.cnf
# - ./conf/php.ini:/etc/php/7.1/fpm/conf.d/40-custom.ini
# command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
